// <auto-generated>
// 此文件由 Tools/Prometheus/Audio/Refresh Banks And Regenerate FMOD Event Enum 生成；请勿手工修改。
// 生成时共发现 10 个 event:/ 音频事件，枚举值来自稳定路径哈希，运行时通过 GUID 播放。
// </auto-generated>
using FMOD;

namespace Xuan.Prometheus
{
    /// <summary>定义从当前 FMOD Bank 缓存生成的稳定音频事件标识。</summary>
    public enum FmodAudioEvent
    {
        /// <summary>表示不绑定任何 FMOD 音频事件。</summary>
        None = 0,
        /// <summary>FMOD 事件 event:/Combat/Enemy/Slime_Attack。</summary>
        CombatEnemySlime_Attack = 1382085073,
        /// <summary>FMOD 事件 event:/Combat/Library/Sword_Whoosh。</summary>
        CombatLibrarySword_Whoosh = 1536815977,
        /// <summary>FMOD 事件 event:/Combat/Player/Normal_Attack_01。</summary>
        CombatPlayerNormal_Attack_01 = 1471328291,
        /// <summary>FMOD 事件 event:/Combat/Player/Normal_Attack_02。</summary>
        CombatPlayerNormal_Attack_02 = 1488105910,
        /// <summary>FMOD 事件 event:/Combat/Player/Normal_Attack_03。</summary>
        CombatPlayerNormal_Attack_03 = 1504883529,
        /// <summary>FMOD 事件 event:/Combat/Player/Normal_Attack_04。</summary>
        CombatPlayerNormal_Attack_04 = 1521661148,
        /// <summary>FMOD 事件 event:/Combat/Player/Skill。</summary>
        CombatPlayerSkill = 1186598182,
        /// <summary>FMOD 事件 event:/Combat/Player/Special_Attack。</summary>
        CombatPlayerSpecial_Attack = 91704277,
        /// <summary>FMOD 事件 event:/Combat/Player/Ultimate。</summary>
        CombatPlayerUltimate = 1502931542,
        /// <summary>FMOD 事件 event:/Combat/Shared/Hit_Flesh。</summary>
        CombatSharedHit_Flesh = 1943874567,
    }

    /// <summary>保存生成的音频事件标识到 FMOD GUID 的运行时映射。</summary>
    internal static class FmodAudioEventCatalog
    {
        /// <summary>尝试解析音频事件对应的稳定 FMOD GUID。</summary>
        public static bool TryGetGuid(FmodAudioEvent audioEvent, out GUID guid)
        {
            switch (audioEvent)
            {
                case FmodAudioEvent.CombatEnemySlime_Attack:
                    guid = new GUID { Data1 = 521153384, Data2 = 1111177039, Data3 = 1153575566, Data4 = 1402626677 };
                    return true;
                case FmodAudioEvent.CombatLibrarySword_Whoosh:
                    guid = new GUID { Data1 = 2122149723, Data2 = 1327854158, Data3 = -1897755755, Data4 = 1570643694 };
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_01:
                    guid = new GUID { Data1 = 587202102, Data2 = 1086318467, Data3 = 1006825858, Data4 = 917213050 };
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_02:
                    guid = new GUID { Data1 = -1108762593, Data2 = 1307333271, Data3 = -2045308280, Data4 = 1103819245 };
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_03:
                    guid = new GUID { Data1 = -476811712, Data2 = 1237460203, Data3 = 413153962, Data4 = 1528675749 };
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_04:
                    guid = new GUID { Data1 = -1871662089, Data2 = 1092237636, Data3 = -2028892797, Data4 = 842888658 };
                    return true;
                case FmodAudioEvent.CombatPlayerSkill:
                    guid = new GUID { Data1 = -662187257, Data2 = 1311638394, Data3 = -553998205, Data4 = 947644553 };
                    return true;
                case FmodAudioEvent.CombatPlayerSpecial_Attack:
                    guid = new GUID { Data1 = -1827568823, Data2 = 1264585466, Data3 = 119546764, Data4 = -1330105577 };
                    return true;
                case FmodAudioEvent.CombatPlayerUltimate:
                    guid = new GUID { Data1 = 2030136426, Data2 = 1099892415, Data3 = -430240086, Data4 = 2057710426 };
                    return true;
                case FmodAudioEvent.CombatSharedHit_Flesh:
                    guid = new GUID { Data1 = 1378848227, Data2 = 1081097514, Data3 = -1706301035, Data4 = 994028332 };
                    return true;
                default:
                    guid = default;
                    return false;
            }
        }

#if UNITY_EDITOR
        /// <summary>尝试解析编辑器中用于诊断和展示的 FMOD 事件路径。</summary>
        public static bool TryGetPath(FmodAudioEvent audioEvent, out string path)
        {
            switch (audioEvent)
            {
                case FmodAudioEvent.CombatEnemySlime_Attack:
                    path = "event:/Combat/Enemy/Slime_Attack";
                    return true;
                case FmodAudioEvent.CombatLibrarySword_Whoosh:
                    path = "event:/Combat/Library/Sword_Whoosh";
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_01:
                    path = "event:/Combat/Player/Normal_Attack_01";
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_02:
                    path = "event:/Combat/Player/Normal_Attack_02";
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_03:
                    path = "event:/Combat/Player/Normal_Attack_03";
                    return true;
                case FmodAudioEvent.CombatPlayerNormal_Attack_04:
                    path = "event:/Combat/Player/Normal_Attack_04";
                    return true;
                case FmodAudioEvent.CombatPlayerSkill:
                    path = "event:/Combat/Player/Skill";
                    return true;
                case FmodAudioEvent.CombatPlayerSpecial_Attack:
                    path = "event:/Combat/Player/Special_Attack";
                    return true;
                case FmodAudioEvent.CombatPlayerUltimate:
                    path = "event:/Combat/Player/Ultimate";
                    return true;
                case FmodAudioEvent.CombatSharedHit_Flesh:
                    path = "event:/Combat/Shared/Hit_Flesh";
                    return true;
                default:
                    path = string.Empty;
                    return false;
            }
        }
#endif
    }
}
